#ifndef _USR_GENERAL_DEFINES_H_
#define _USR_GENERAL_DEFINES_H_

#define QUADRO_SHUNT_MODULE_REQUEST_CAN_ID 0x100
#define MAIN_SHUNT_MODULE_REQUEST_CAN_ID 0x200
#define SENSOR_MODULE_REQUEST_CAN_ID 0x300

#define BUTTON_1_REQUEST_CAN_ID 0x400
#define BUTTON_2_REQUEST_CAN_ID 0x401
#define BUTTON_3_REQUEST_CAN_ID 0x402
#define BUTTON_4_REQUEST_CAN_ID 0x403
#define BUTTON_5_REQUEST_CAN_ID 0x404
#define BUTTON_6_REQUEST_CAN_ID 0x405

#define QUADRO_SHUNT_MODULE_RESPONSE_CAN_ID 0x180
#define MAIN_SHUNT_MODULE_RESPONSE_CAN_ID 0x280
#define SENSOR_MODULE_RESPONSE_CAN_ID 0x380

#define BUTTON_1_RESPONSE_CAN_ID 0x480
#define BUTTON_2_RESPONSE_CAN_ID 0x481
#define BUTTON_3_RESPONSE_CAN_ID 0x482
#define BUTTON_4_RESPONSE_CAN_ID 0x483
#define BUTTON_5_RESPONSE_CAN_ID 0x484
#define BUTTON_6_RESPONSE_CAN_ID 0x485

#define QUADRO_SHUNT_MODULE_CAN_ID QUADRO_SHUNT_MODULE_RESPONSE_CAN_ID
#define MAIN_SHUNT_MODULE_CAN_ID MAIN_SHUNT_MODULE_RESPONSE_CAN_ID
#define SENSOR_MODULE_CAN_ID SENSOR_MODULE_RESPONSE_CAN_ID
#define BUTTON_1_ID BUTTON_1_RESPONSE_CAN_ID
#define BUTTON_2_ID BUTTON_2_RESPONSE_CAN_ID
#define BUTTON_3_ID BUTTON_3_RESPONSE_CAN_ID
#define BUTTON_4_ID BUTTON_4_RESPONSE_CAN_ID
#define BUTTON_5_ID BUTTON_5_RESPONSE_CAN_ID
#define BUTTON_6_ID BUTTON_6_RESPONSE_CAN_ID

#define REQUEST_CMD         0x01
#define RESPONSE_CMD        0x02
#define HEARTBEAT_CMD       0x03

#define DATA_TYPE_SENSOR    0x01
#define DATA_TYPE_STATUS    0x02
#define DATA_TYPE_VOLTAGE   0x03
#define DATA_TYPE_CURRENT   0x04

#define BUTTON_1_ON 0x01
#define BUTTON_1_OFF 0x00

#define BUTTON_2_ON 0x01
#define BUTTON_2_OFF 0x00

#define BUTTON_3_ON 0x01
#define BUTTON_3_OFF 0x00

#define BUTTON_4_ON 0x01
#define BUTTON_4_OFF 0x00

#define BUTTON_5_ON 0x01
#define BUTTON_5_OFF 0x00

#define BUTTON_6_ON 0x01
#define BUTTON_6_OFF 0x00

#endif /*_USR_GENERAL_DEFINES_H_*/